//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 11:55:29 PM EEST 
//


package libraryService.interfaces;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the libraryService.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: libraryService.interfaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllBooksRequest }
     * 
     */
    public GetAllBooksRequest createGetAllBooksRequest() {
        return new GetAllBooksRequest();
    }

    /**
     * Create an instance of {@link GetAllBooksResponse }
     * 
     */
    public GetAllBooksResponse createGetAllBooksResponse() {
        return new GetAllBooksResponse();
    }

    /**
     * Create an instance of {@link BookInfo }
     * 
     */
    public BookInfo createBookInfo() {
        return new BookInfo();
    }

    /**
     * Create an instance of {@link GetBookByIdRequest }
     * 
     */
    public GetBookByIdRequest createGetBookByIdRequest() {
        return new GetBookByIdRequest();
    }

    /**
     * Create an instance of {@link GetBookByIdResponse }
     * 
     */
    public GetBookByIdResponse createGetBookByIdResponse() {
        return new GetBookByIdResponse();
    }

    /**
     * Create an instance of {@link AddBookRequest }
     * 
     */
    public AddBookRequest createAddBookRequest() {
        return new AddBookRequest();
    }

    /**
     * Create an instance of {@link PlantInfoWithoutId }
     * 
     */
    public PlantInfoWithoutId createPlantInfoWithoutId() {
        return new PlantInfoWithoutId();
    }

    /**
     * Create an instance of {@link AddBookResponse }
     * 
     */
    public AddBookResponse createAddBookResponse() {
        return new AddBookResponse();
    }

    /**
     * Create an instance of {@link UpdateBookRequest }
     * 
     */
    public UpdateBookRequest createUpdateBookRequest() {
        return new UpdateBookRequest();
    }

    /**
     * Create an instance of {@link BookInfoPlantIdOptional }
     * 
     */
    public BookInfoPlantIdOptional createBookInfoPlantIdOptional() {
        return new BookInfoPlantIdOptional();
    }

    /**
     * Create an instance of {@link UpdateBookResponse }
     * 
     */
    public UpdateBookResponse createUpdateBookResponse() {
        return new UpdateBookResponse();
    }

    /**
     * Create an instance of {@link DeleteBookRequest }
     * 
     */
    public DeleteBookRequest createDeleteBookRequest() {
        return new DeleteBookRequest();
    }

    /**
     * Create an instance of {@link DeleteBookResponse }
     * 
     */
    public DeleteBookResponse createDeleteBookResponse() {
        return new DeleteBookResponse();
    }

    /**
     * Create an instance of {@link BookId }
     * 
     */
    public BookId createBookId() {
        return new BookId();
    }

    /**
     * Create an instance of {@link PlantInfo }
     * 
     */
    public PlantInfo createPlantInfo() {
        return new PlantInfo();
    }

    /**
     * Create an instance of {@link PlantInfoWithOptionalId }
     * 
     */
    public PlantInfoWithOptionalId createPlantInfoWithOptionalId() {
        return new PlantInfoWithOptionalId();
    }

    /**
     * Create an instance of {@link GetAllLibrariesRequest }
     * 
     */
    public GetAllLibrariesRequest createGetAllLibrariesRequest() {
        return new GetAllLibrariesRequest();
    }

    /**
     * Create an instance of {@link GetAllLibrariesResponse }
     * 
     */
    public GetAllLibrariesResponse createGetAllLibrariesResponse() {
        return new GetAllLibrariesResponse();
    }

    /**
     * Create an instance of {@link LibraryInfo }
     * 
     */
    public LibraryInfo createLibraryInfo() {
        return new LibraryInfo();
    }

    /**
     * Create an instance of {@link GetLibraryByIdRequest }
     * 
     */
    public GetLibraryByIdRequest createGetLibraryByIdRequest() {
        return new GetLibraryByIdRequest();
    }

    /**
     * Create an instance of {@link GetLibraryByIdResponse }
     * 
     */
    public GetLibraryByIdResponse createGetLibraryByIdResponse() {
        return new GetLibraryByIdResponse();
    }

    /**
     * Create an instance of {@link AddLibraryRequest }
     * 
     */
    public AddLibraryRequest createAddLibraryRequest() {
        return new AddLibraryRequest();
    }

    /**
     * Create an instance of {@link AddLibraryResponse }
     * 
     */
    public AddLibraryResponse createAddLibraryResponse() {
        return new AddLibraryResponse();
    }

    /**
     * Create an instance of {@link UpdateLibraryRequest }
     * 
     */
    public UpdateLibraryRequest createUpdateLibraryRequest() {
        return new UpdateLibraryRequest();
    }

    /**
     * Create an instance of {@link UpdateLibraryResponse }
     * 
     */
    public UpdateLibraryResponse createUpdateLibraryResponse() {
        return new UpdateLibraryResponse();
    }

    /**
     * Create an instance of {@link UpdateLibraryBooksRequest }
     * 
     */
    public UpdateLibraryBooksRequest createUpdateLibraryBooksRequest() {
        return new UpdateLibraryBooksRequest();
    }

    /**
     * Create an instance of {@link UpdateLibraryBooksResponse }
     * 
     */
    public UpdateLibraryBooksResponse createUpdateLibraryBooksResponse() {
        return new UpdateLibraryBooksResponse();
    }

    /**
     * Create an instance of {@link DeleteLibraryRequest }
     * 
     */
    public DeleteLibraryRequest createDeleteLibraryRequest() {
        return new DeleteLibraryRequest();
    }

    /**
     * Create an instance of {@link DeleteLibraryResponse }
     * 
     */
    public DeleteLibraryResponse createDeleteLibraryResponse() {
        return new DeleteLibraryResponse();
    }

    /**
     * Create an instance of {@link RemoveBookFromLibraryRequest }
     * 
     */
    public RemoveBookFromLibraryRequest createRemoveBookFromLibraryRequest() {
        return new RemoveBookFromLibraryRequest();
    }

    /**
     * Create an instance of {@link RemoveBookFromLibraryResponse }
     * 
     */
    public RemoveBookFromLibraryResponse createRemoveBookFromLibraryResponse() {
        return new RemoveBookFromLibraryResponse();
    }

}
