//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 11:55:29 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.library_service.com/library", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package libraryService.interfaces;
